a= int(input("Enter first number "))
b = int(input("Enter second number "))
print("Addition of ",a, "+",b, "=", a+b)
print("Substraction of ",a, "-",b, "=", a-b)
print("Multiplication of ",a, "*",b, "=", a*b)
print("Division of ",a, "/",b, "=", a/b)